# Generated by Django 3.1.5 on 2021-01-21 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('historico', '0001_initial'),
        ('agrupamentos', '0001_initial'),
        ('raca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacao', models.CharField(max_length=255)),
                ('descricao', models.TextField(max_length=255)),
                ('cod_agrupamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agrupamentos.agrupamento')),
                ('cod_historico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='historico.historico')),
                ('cod_raca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raca.raca')),
            ],
        ),
    ]
