# Generated by Django 3.1.5 on 2021-01-14 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('historico_tipo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('data', models.DateField(verbose_name='Data')),
                ('cod_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='historico_tipo.historico_tipo')),
            ],
        ),
    ]
