# Generated by Django 3.1.5 on 2021-01-22 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historico', '0002_auto_20210122_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historico',
            name='descricao',
            field=models.TextField(max_length=255),
        ),
    ]
