# Generated by Django 3.1.5 on 2021-01-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historico_tipo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historico_tipo',
            name='descricao',
            field=models.TextField(max_length=255),
        ),
    ]
