# Generated by Django 3.1.5 on 2021-01-21 23:28

from django.db import migrations, models
import django.db.models.deletion
import imagens.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animais', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to=imagens.models.upload_imagem)),
                ('cod_animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animais.animal')),
            ],
        ),
    ]
