# Generated by Django 3.1.5 on 2021-01-17 14:15

from django.db import migrations, models
import imagens.models


class Migration(migrations.Migration):

    dependencies = [
        ('imagens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagens',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=imagens.models.upload_imagem),
        ),
    ]
