# Generated by Django 3.1.5 on 2021-01-17 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imagens', '0002_imagens_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagens',
            name='path',
        ),
    ]
